export type GameRecord = {
  id: number;
  game_id: number;
  player_id: number;
  madeFG: number;
  attemptFG: number;
  made2PTS: number;
  attempt2PTS: number;
  made3PTS: number;
  attempt3PTS: number;
  madeFT: number;
  attemptFT: number;
  offRebound: number;
  defRebound: number;
  assists: number;
  steals: number;
  blocks: number;
  turnovers: number;
  fouls: number;
  points: number;
};

// game_records.ts
const game_record: GameRecord[] = [
  {
    id: 1,
    game_id: 1,
    player_id: 1,
    madeFG: 3,
    attemptFG: 10,
    made2PTS: 2,
    attempt2PTS: 5,
    made3PTS: 1,
    attempt3PTS: 5,
    madeFT: 2,
    attemptFT: 4,
    offRebound: 2,
    defRebound: 5,
    assists: 3,
    steals: 1,
    blocks: 0,
    turnovers: 1,
    fouls: 2,
    points: 11,
  },
  {
    id: 2,
    game_id: 1,
    player_id: 2,
    madeFG: 5,
    attemptFG: 15,
    made2PTS: 4,
    attempt2PTS: 10,
    made3PTS: 1,
    attempt3PTS: 5,
    madeFT: 3,
    attemptFT: 6,
    offRebound: 3,
    defRebound: 4,
    assists: 4,
    steals: 0,
    blocks: 1,
    turnovers: 2,
    fouls: 3,
    points: 17,
  },
  {
    id: 3,
    game_id: 1,
    player_id: 3,
    madeFG: 2,
    attemptFG: 8,
    made2PTS: 1,
    attempt2PTS: 4,
    made3PTS: 1,
    attempt3PTS: 4,
    madeFT: 1,
    attemptFT: 2,
    offRebound: 1,
    defRebound: 3,
    assists: 2,
    steals: 1,
    blocks: 0,
    turnovers: 1,
    fouls: 2,
    points: 8,
  },
  {
    id: 4,
    game_id: 1,
    player_id: 4,
    madeFG: 4,
    attemptFG: 12,
    made2PTS: 3,
    attempt2PTS: 8,
    made3PTS: 1,
    attempt3PTS: 4,
    madeFT: 2,
    attemptFT: 4,
    offRebound: 2,
    defRebound: 5,
    assists: 3,
    steals: 1,
    blocks: 0,
    turnovers: 1,
    fouls: 2,
    points: 13,
  },
  {
    id: 5,
    game_id: 1,
    player_id: 5,
    madeFG: 3,
    attemptFG: 10,
    made2PTS: 2,
    attempt2PTS: 5,
    made3PTS: 1,
    attempt3PTS: 5,
    madeFT: 1,
    attemptFT: 2,
    offRebound: 1,
    defRebound: 3,
    assists: 2,
    steals: 1,
    blocks: 0,
    turnovers: 1,
    fouls: 2,
    points: 10,
  },
  {
    id: 6,
    game_id: 1,
    player_id: 6,
    madeFG: 2,
    attemptFG: 8,
    made2PTS: 1,
    attempt2PTS: 4,
    made3PTS: 1,
    attempt3PTS: 4,
    madeFT: 1,
    attemptFT: 2,
    offRebound: 1,
    defRebound: 3,
    assists: 2,
    steals: 1,
    blocks: 0,
    turnovers: 1,
    fouls: 2,
    points: 8,
  },
  {
    id: 7,
    game_id: 1,
    player_id: 7,
    madeFG: 4,
    attemptFG: 12,
    made2PTS: 3,
    attempt2PTS: 8,
    made3PTS: 1,
    attempt3PTS: 4,
    madeFT: 2,
    attemptFT: 4,
    offRebound: 2,
    defRebound: 5,
    assists: 3,
    steals: 1,
    blocks: 0,
    turnovers: 1,
    fouls: 2,
    points: 13,
  },
  // Game 2
  {
    id: 8,
    game_id: 2,
    player_id: 1,
    madeFG: 2,
    attemptFG: 9,
    made2PTS: 1,
    attempt2PTS: 4,
    made3PTS: 1,
    attempt3PTS: 5,
    madeFT: 1,
    attemptFT: 2,
    offRebound: 1,
    defRebound: 4,
    assists: 2,
    steals: 1,
    blocks: 0,
    turnovers: 1,
    fouls: 2,
    points: 8,
  },
  {
    id: 9,
    game_id: 2,
    player_id: 2,
    madeFG: 6,
    attemptFG: 18,
    made2PTS: 5,
    attempt2PTS: 12,
    made3PTS: 1,
    attempt3PTS: 6,
    madeFT: 3,
    attemptFT: 6,
    offRebound: 3,
    defRebound: 5,
    assists: 4,
    steals: 0,
    blocks: 1,
    turnovers: 2,
    fouls: 3,
    points: 20,
  },
  {
    id: 10,
    game_id: 2,
    player_id: 3,
    madeFG: 3,
    attemptFG: 11,
    made2PTS: 2,
    attempt2PTS: 6,
    made3PTS: 1,
    attempt3PTS: 5,
    madeFT: 2,
    attemptFT: 4,
    offRebound: 2,
    defRebound: 4,
    assists: 3,
    steals: 1,
    blocks: 0,
    turnovers: 1,
    fouls: 2,
    points: 12,
  },
  {
    id: 11,
    game_id: 2,
    player_id: 4,
    madeFG: 5,
    attemptFG: 15,
    made2PTS: 4,
    attempt2PTS: 10,
    made3PTS: 1,
    attempt3PTS: 5,
    madeFT: 2,
    attemptFT: 4,
    offRebound: 2,
    defRebound: 5,
    assists: 3,
    steals: 1,
    blocks: 0,
    turnovers: 1,
    fouls: 2,
    points: 16,
  },
  {
    id: 12,
    game_id: 2,
    player_id: 5,
    madeFG: 2,
    attemptFG: 9,
    made2PTS: 1,
    attempt2PTS: 4,
    made3PTS: 1,
    attempt3PTS: 5,
    madeFT: 1,
    attemptFT: 2,
    offRebound: 1,
    defRebound: 4,
    assists: 2,
    steals: 1,
    blocks: 0,
    turnovers: 1,
    fouls: 2,
    points: 8,
  },
  {
    id: 13,
    game_id: 2,
    player_id: 6,
    madeFG: 3,
    attemptFG: 11,
    made2PTS: 2,
    attempt2PTS: 6,
    made3PTS: 1,
    attempt3PTS: 5,
    madeFT: 2,
    attemptFT: 4,
    offRebound: 2,
    defRebound: 4,
    assists: 3,
    steals: 1,
    blocks: 0,
    turnovers: 1,
    fouls: 2,
    points: 12,
  },
  {
    id: 14,
    game_id: 2,
    player_id: 7,
    madeFG: 4,
    attemptFG: 14,
    made2PTS: 3,
    attempt2PTS: 9,
    made3PTS: 1,
    attempt3PTS: 5,
    madeFT: 2,
    attemptFT: 4,
    offRebound: 2,
    defRebound: 5,
    assists: 3,
    steals: 1,
    blocks: 0,
    turnovers: 1,
    fouls: 2,
    points: 14,
  },
  // Game 3
  {
    id: 15,
    game_id: 3,
    player_id: 1,
    madeFG: 3,
    attemptFG: 10,
    made2PTS: 2,
    attempt2PTS: 5,
    made3PTS: 1,
    attempt3PTS: 5,
    madeFT: 2,
    attemptFT: 4,
    offRebound: 2,
    defRebound: 5,
    assists: 3,
    steals: 1,
    blocks: 0,
    turnovers: 1,
    fouls: 2,
    points: 12,
  },
  {
    id: 16,
    game_id: 3,
    player_id: 2,
    madeFG: 5,
    attemptFG: 16,
    made2PTS: 4,
    attempt2PTS: 10,
    made3PTS: 1,
    attempt3PTS: 6,
    madeFT: 3,
    attemptFT: 6,
    offRebound: 3,
    defRebound: 5,
    assists: 4,
    steals: 0,
    blocks: 1,
    turnovers: 2,
    fouls: 3,
    points: 18,
  },
  {
    id: 17,
    game_id: 3,
    player_id: 3,
    madeFG: 2,
    attemptFG: 9,
    made2PTS: 1,
    attempt2PTS: 4,
    made3PTS: 1,
    attempt3PTS: 5,
    madeFT: 1,
    attemptFT: 2,
    offRebound: 1,
    defRebound: 4,
    assists: 2,
    steals: 1,
    blocks: 0,
    turnovers: 1,
    fouls: 2,
    points: 8,
  },
  {
    id: 18,
    game_id: 3,
    player_id: 4,
    madeFG: 4,
    attemptFG: 14,
    made2PTS: 3,
    attempt2PTS: 9,
    made3PTS: 1,
    attempt3PTS: 5,
    madeFT: 2,
    attemptFT: 4,
    offRebound: 2,
    defRebound: 5,
    assists: 3,
    steals: 1,
    blocks: 0,
    turnovers: 1,
    fouls: 2,
    points: 14,
  },
  {
    id: 19,
    game_id: 3,
    player_id: 5,
    madeFG: 3,
    attemptFG: 11,
    made2PTS: 2,
    attempt2PTS: 6,
    made3PTS: 1,
    attempt3PTS: 5,
    madeFT: 2,
    attemptFT: 4,
    offRebound: 2,
    defRebound: 4,
    assists: 3,
    steals: 1,
    blocks: 0,
    turnovers: 1,
    fouls: 2,
    points: 12,
  },
  {
    id: 20,
    game_id: 3,
    player_id: 6,
    madeFG: 2,
    attemptFG: 9,
    made2PTS: 1,
    attempt2PTS: 4,
    made3PTS: 1,
    attempt3PTS: 5,
    madeFT: 1,
    attemptFT: 2,
    offRebound: 1,
    defRebound: 4,
    assists: 2,
    steals: 1,
    blocks: 0,
    turnovers: 1,
    fouls: 2,
    points: 8,
  },
  {
    id: 21,
    game_id: 3,
    player_id: 7,
    madeFG: 5,
    attemptFG: 16,
    made2PTS: 4,
    attempt2PTS: 10,
    made3PTS: 1,
    attempt3PTS: 6,
    madeFT: 3,
    attemptFT: 6,
    offRebound: 3,
    defRebound: 5,
    assists: 4,
    steals: 0,
    blocks: 1,
    turnovers: 2,
    fouls: 3,
    points: 18,
  },
  // --- Start of Game 4 ---
  {
    id: 22,
    game_id: 4,
    player_id: 1,
    madeFG: 4,
    attemptFG: 12,
    made2PTS: 3,
    attempt2PTS: 7,
    made3PTS: 1,
    attempt3PTS: 5,
    madeFT: 3,
    attemptFT: 4,
    offRebound: 1,
    defRebound: 6,
    assists: 4,
    steals: 2,
    blocks: 0,
    turnovers: 2,
    fouls: 1,
    points: 14,
  },
  {
    id: 23,
    game_id: 4,
    player_id: 2,
    madeFG: 7,
    attemptFG: 18,
    made2PTS: 6,
    attempt2PTS: 13,
    made3PTS: 1,
    attempt3PTS: 5,
    madeFT: 4,
    attemptFT: 8,
    offRebound: 2,
    defRebound: 6,
    assists: 5,
    steals: 1,
    blocks: 1,
    turnovers: 3,
    fouls: 2,
    points: 21,
  },
  {
    id: 24,
    game_id: 4,
    player_id: 3,
    madeFG: 3,
    attemptFG: 10,
    made2PTS: 1,
    attempt2PTS: 5,
    made3PTS: 2,
    attempt3PTS: 5,
    madeFT: 1,
    attemptFT: 2,
    offRebound: 1,
    defRebound: 3,
    assists: 2,
    steals: 0,
    blocks: 0,
    turnovers: 1,
    fouls: 2,
    points: 11,
  },
  {
    id: 25,
    game_id: 4,
    player_id: 4,
    madeFG: 5,
    attemptFG: 13,
    made2PTS: 4,
    attempt2PTS: 8,
    made3PTS: 1,
    attempt3PTS: 5,
    madeFT: 2,
    attemptFT: 3,
    offRebound: 3,
    defRebound: 4,
    assists: 3,
    steals: 1,
    blocks: 0,
    turnovers: 1,
    fouls: 3,
    points: 14,
  },
  {
    id: 26,
    game_id: 4,
    player_id: 5,
    madeFG: 2,
    attemptFG: 8,
    made2PTS: 1,
    attempt2PTS: 3,
    made3PTS: 1,
    attempt3PTS: 5,
    madeFT: 1,
    attemptFT: 2,
    offRebound: 1,
    defRebound: 4,
    assists: 2,
    steals: 1,
    blocks: 0,
    turnovers: 1,
    fouls: 2,
    points: 8,
  },
  {
    id: 27,
    game_id: 4,
    player_id: 6,
    madeFG: 4,
    attemptFG: 11,
    made2PTS: 3,
    attempt2PTS: 6,
    made3PTS: 1,
    attempt3PTS: 5,
    madeFT: 2,
    attemptFT: 4,
    offRebound: 2,
    defRebound: 4,
    assists: 3,
    steals: 1,
    blocks: 0,
    turnovers: 1,
    fouls: 2,
    points: 13,
  },
  {
    id: 28,
    game_id: 4,
    player_id: 7,
    madeFG: 6,
    attemptFG: 15,
    made2PTS: 4,
    attempt2PTS: 8,
    made3PTS: 2,
    attempt3PTS: 7,
    madeFT: 1,
    attemptFT: 2,
    offRebound: 2,
    defRebound: 5,
    assists: 4,
    steals: 1,
    blocks: 1,
    turnovers: 2,
    fouls: 2,
    points: 15,
  },

  // --- Start of Game 5 ---
  {
    id: 29,
    game_id: 5,
    player_id: 1,
    madeFG: 3,
    attemptFG: 9,
    made2PTS: 2,
    attempt2PTS: 4,
    made3PTS: 1,
    attempt3PTS: 5,
    madeFT: 2,
    attemptFT: 2,
    offRebound: 1,
    defRebound: 5,
    assists: 3,
    steals: 1,
    blocks: 0,
    turnovers: 1,
    fouls: 2,
    points: 11,
  },
  {
    id: 30,
    game_id: 5,
    player_id: 2,
    madeFG: 6,
    attemptFG: 17,
    made2PTS: 5,
    attempt2PTS: 11,
    made3PTS: 1,
    attempt3PTS: 6,
    madeFT: 2,
    attemptFT: 4,
    offRebound: 3,
    defRebound: 7,
    assists: 6,
    steals: 1,
    blocks: 0,
    turnovers: 3,
    fouls: 3,
    points: 19,
  },
  {
    id: 31,
    game_id: 5,
    player_id: 3,
    madeFG: 2,
    attemptFG: 7,
    made2PTS: 1,
    attempt2PTS: 3,
    made3PTS: 1,
    attempt3PTS: 4,
    madeFT: 2,
    attemptFT: 4,
    offRebound: 1,
    defRebound: 3,
    assists: 2,
    steals: 1,
    blocks: 0,
    turnovers: 1,
    fouls: 2,
    points: 7,
  },
  {
    id: 32,
    game_id: 5,
    player_id: 4,
    madeFG: 4,
    attemptFG: 13,
    made2PTS: 3,
    attempt2PTS: 7,
    made3PTS: 1,
    attempt3PTS: 6,
    madeFT: 1,
    attemptFT: 2,
    offRebound: 2,
    defRebound: 4,
    assists: 3,
    steals: 1,
    blocks: 0,
    turnovers: 1,
    fouls: 2,
    points: 12,
  },
  {
    id: 33,
    game_id: 5,
    player_id: 5,
    madeFG: 3,
    attemptFG: 10,
    made2PTS: 2,
    attempt2PTS: 5,
    made3PTS: 1,
    attempt3PTS: 5,
    madeFT: 1,
    attemptFT: 2,
    offRebound: 1,
    defRebound: 3,
    assists: 2,
    steals: 1,
    blocks: 0,
    turnovers: 1,
    fouls: 2,
    points: 10,
  },
  {
    id: 34,
    game_id: 5,
    player_id: 6,
    madeFG: 2,
    attemptFG: 8,
    made2PTS: 1,
    attempt2PTS: 4,
    made3PTS: 1,
    attempt3PTS: 4,
    madeFT: 1,
    attemptFT: 2,
    offRebound: 1,
    defRebound: 3,
    assists: 2,
    steals: 1,
    blocks: 0,
    turnovers: 1,
    fouls: 2,
    points: 8,
  },
  {
    id: 35,
    game_id: 5,
    player_id: 7,
    madeFG: 5,
    attemptFG: 15,
    made2PTS: 3,
    attempt2PTS: 7,
    made3PTS: 2,
    attempt3PTS: 8,
    madeFT: 3,
    attemptFT: 4,
    offRebound: 1,
    defRebound: 6,
    assists: 5,
    steals: 1,
    blocks: 1,
    turnovers: 2,
    fouls: 2,
    points: 15,
  },

  // --- Start of Game 6 ---
  {
    id: 36,
    game_id: 6,
    player_id: 1,
    madeFG: 4,
    attemptFG: 11,
    made2PTS: 3,
    attempt2PTS: 6,
    made3PTS: 1,
    attempt3PTS: 5,
    madeFT: 1,
    attemptFT: 2,
    offRebound: 2,
    defRebound: 5,
    assists: 3,
    steals: 1,
    blocks: 0,
    turnovers: 1,
    fouls: 2,
    points: 12,
  },
  {
    id: 37,
    game_id: 6,
    player_id: 2,
    madeFG: 7,
    attemptFG: 16,
    made2PTS: 6,
    attempt2PTS: 10,
    made3PTS: 1,
    attempt3PTS: 6,
    madeFT: 5,
    attemptFT: 10,
    offRebound: 4,
    defRebound: 6,
    assists: 5,
    steals: 2,
    blocks: 1,
    turnovers: 2,
    fouls: 4,
    points: 20,
  },
  {
    id: 38,
    game_id: 6,
    player_id: 3,
    madeFG: 3,
    attemptFG: 9,
    made2PTS: 2,
    attempt2PTS: 5,
    made3PTS: 1,
    attempt3PTS: 4,
    madeFT: 2,
    attemptFT: 2,
    offRebound: 1,
    defRebound: 4,
    assists: 2,
    steals: 1,
    blocks: 0,
    turnovers: 1,
    fouls: 2,
    points: 10,
  },
  {
    id: 39,
    game_id: 6,
    player_id: 4,
    madeFG: 5,
    attemptFG: 14,
    made2PTS: 3,
    attempt2PTS: 7,
    made3PTS: 2,
    attempt3PTS: 7,
    madeFT: 2,
    attemptFT: 4,
    offRebound: 3,
    defRebound: 5,
    assists: 4,
    steals: 1,
    blocks: 0,
    turnovers: 1,
    fouls: 3,
    points: 16,
  },
  {
    id: 40,
    game_id: 6,
    player_id: 5,
    madeFG: 2,
    attemptFG: 7,
    made2PTS: 1,
    attempt2PTS: 3,
    made3PTS: 1,
    attempt3PTS: 4,
    madeFT: 1,
    attemptFT: 2,
    offRebound: 1,
    defRebound: 3,
    assists: 2,
    steals: 1,
    blocks: 0,
    turnovers: 1,
    fouls: 2,
    points: 8,
  },
  {
    id: 41,
    game_id: 6,
    player_id: 6,
    madeFG: 3,
    attemptFG: 10,
    made2PTS: 2,
    attempt2PTS: 5,
    made3PTS: 1,
    attempt3PTS: 5,
    madeFT: 2,
    attemptFT: 4,
    offRebound: 2,
    defRebound: 4,
    assists: 3,
    steals: 1,
    blocks: 0,
    turnovers: 1,
    fouls: 2,
    points: 12,
  },
  {
    id: 42,
    game_id: 6,
    player_id: 7,
    madeFG: 6,
    attemptFG: 17,
    made2PTS: 4,
    attempt2PTS: 9,
    made3PTS: 2,
    attempt3PTS: 8,
    madeFT: 2,
    attemptFT: 4,
    offRebound: 3,
    defRebound: 5,
    assists: 4,
    steals: 1,
    blocks: 1,
    turnovers: 2,
    fouls: 2,
    points: 16,
  },
];

export default game_record;
